rag_ingest_task:
  description: >
    Take a user document (raw text or uploaded file), split it into chunks, 
    create embeddings using the user's selected embedding model, and store them in the vector database.
  expected_output: >
    Confirmation that embeddings have been successfully stored in the vector DB.
  agent: rag_agent

rag_retrieve_task:
  description: >
    You must use the exact user query provided in the inputs to search the vector database.
    The user query is: {query}
    Do NOT make assumptions about the query. Use ONLY the provided query: {query}
    Retrieve the top-3 most relevant document chunks using semantic similarity search.
  expected_output: >
    A JSON list of retrieved chunks with their similarity scores and text content for the query: {query}
  agent: rag_agent